version: '3.4'
services:
  client:
    image: debian
    build:
      context: ./
      dockerfile: client.Dockerfile
    command:
      - /bin/bash
      - -c
      - seq 999999 | parallel --halt soon,fail=99% -j10 "curl --max-time 3 --fail -so/dev/null http://web:8080/{}"

  web:
    build:
      context: ../
    environment:
      API_KEY: xxxx
      MYENV: myenvhere
    command:
      - /usr/bin/openresty
      - -g
      - daemon off;error_log /dev/stderr notice;
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 10254:10254
    - 8080:8080

  back:
    image: openresty/openresty:1.19.9.1-5-bullseye-fat
    volumes:
    - ./back-nginx.conf:/etc/nginx/conf.d/back-nginx.conf
